# Generated by Django 4.1.4 on 2023-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
