# Generated by Django 4.1.4 on 2023-02-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFinal', '0006_rename_comentario_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
