# Generated by Django 4.1.4 on 2023-02-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFinal', '0007_comentario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='publi',
        ),
    ]
